name: Prisma Auto Update

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */2 * * *"   # cada 2 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Actualizar pip
        run: python -m pip install --upgrade pip

      - name: Instalar dependencias
        run: |
          pip install \
          feedparser \
          sentence-transformers \
          numpy \
          scikit-learn

      - name: Debug estructura
        run: ls -la

      - name: Generar p√°gina
        run: python rss_prisma.py

      - name: Commit cambios
        run: |
          git config user.name "Prisma Bot"
          git config user.email "bot@prisma.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto update noticias"
          git push
